version: 2.1
workflows:
  build_test_release:
    jobs:
      - test
      - build
      - release:
          requires:
            - build
            - test
          filters:
            branches:
              only: /^master|dev|[0-9]+\.[0-9]+\.x$/

jobs:
  test:
    docker:
      - image: circleci/node:14.15

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn --frozen-lockfile --ignore-engines

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn run lint
      - run: yarn test -w 1 --coverage
      - run: bash <(curl -s https://codecov.io/bash)

  build:
    docker:
      - image: circleci/node:14.15

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn --frozen-lockfile --ignore-engines

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Build Project
          command: yarn run build
          no_output_timeout: 30m
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - build

  release:
    docker:
      - image: circleci/node:14.15

    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npx semantic-release
